premierleague/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/about', to: 'about#about'
  get '/matchdates', to: 'match_dates#index'
  get '/matchdates/:date', to: 'match_dates#show'
  get 'match_dates/new'
  get 'match_dates/edit'
  get '/referees', to: 'referees#index'
  get '/referees/:refereeId', to: 'referees#show', as: '/referees/show'
  get '/referees/matches/:refereeId', to: 'referees#refereematch'
  get 'referees/new'
  get 'referees/edit'
  get '/matches', to: 'matchs#index'
  get '/search', to: 'matchs#show'
  get 'matchs/new'
  get 'matchs/edit'
  get '/clubs', to: 'clubs#club'
  get '/clubs/:clubname', to: 'clubs#show', as: '/clubs/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

premierleague/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

premierleague/app/models/club.rb
# frozen_string_literal: true

class Club < ApplicationRecord
  self.primary_key = :ClubName
  validates :ClubName, :Played, :Won, :Drawn, :Lost, :GoalFor, :GoalAgainst, :GoalDifference, :Point, presence: true
  validates :Played, :Won, :Drawn, :Lost, :GoalFor, :GoalAgainst, :GoalDifference, :Point, numericality: { only_integer: true }
  # belongs_to :match, foreign_key: 'HomeTeam'
  # belongs_to :match, foreign_key: 'AwayTeam'
end

premierleague/app/models/match.rb
# frozen_string_literal: true

class Match < ApplicationRecord
  self.primary_key = :MatchId
  has_many :clubs
  belongs_to :match_date, foreign_key: 'match_date_id'
  belongs_to :referee, foreign_key: 'referee_id'
  belongs_to :club, foreign_key: 'HomeTeam'
  belongs_to :club, foreign_key: 'AwayTeam'
  validates :Matchid, :HomeTeam, :AwayTeam, :HomeGoal, :AwayGoal, :match_date_id, :referee_id, presence: true
  validates :MatchId, :HomeGoal, :AwayGoal, :referee_id, numericality: { only_integer: true }
end

premierleague/app/models/match_date.rb
# frozen_string_literal: true

class MatchDate < ApplicationRecord
  self.primary_key = :match_date_id
  has_many :matches
  validates :match_date_id, :Temperature, presence: true
  validates :Temperature, numericality: true
end

premierleague/app/models/referee.rb
# frozen_string_literal: true

class Referee < ApplicationRecord
  self.primary_key = :refereeid
  has_many :matchs
  validates :refereeid, :RefereeName, :Age, presence: true
  validates :Age, numericality: { only_integer: true }
end

premierleague/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def about
  end
end

premierleague/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

premierleague/app/controllers/clubs_controller.rb
# frozen_string_literal: true

class ClubsController < ApplicationController
  def club
    @clubs = Club.all

    @page = params[:page]
    @page = 1 if @page.nil?
  end

  def show
    @club = Club.find(params[:clubname])
  end
end

premierleague/app/controllers/match_dates_controller.rb
# frozen_string_literal: true

class MatchDatesController < ApplicationController
  def index
    @matchdates = MatchDate.all

    @page = params[:page]
    @page = 1 if @page.nil?
  end

  def show
    @matchdate = MatchDate.find(params[:date])
    @matches = @matchdate.matches
  end

  def new; end

  def edit; end
end

premierleague/app/controllers/matchs_controller.rb
# frozen_string_literal: true

class MatchsController < ApplicationController
  def index
    @matches = Match.all

    @page = params[:page]
    @page = 1 if @page.nil?
  end

  def show
    @clubsearch = params[:q]
    @count = 0
    @searchmatches = nil

    if !@clubsearch.empty?
      @searchmatches = Match.where('HomeTeam like ? Or AwayTeam like ?',
                                   "%#{@clubsearch}%", "%#{@clubsearch}%")
      @count = @searchmatches.count
    end
  end

  def new; end

  def edit; end
end

premierleague/app/controllers/referees_controller.rb
# frozen_string_literal: true

class RefereesController < ApplicationController
  def index
    @referees = Referee.all
  end

  def show
    @referee = Referee.find(params[:refereeId])
  end

  def refereematch
    @referee = Referee.find(params[:refereeId])
    @matches = @referee.matchs
  end

  def new; end

  def edit; end
end

premierleague/app/helpers/about_helper.rb
module AboutHelper
end

premierleague/app/helpers/application_helper.rb
module ApplicationHelper
end

premierleague/app/helpers/clubs_helper.rb
module ClubsHelper
end

premierleague/app/helpers/match_dates_helper.rb
module MatchDatesHelper
end

premierleague/app/helpers/matchs_helper.rb
module MatchsHelper
end

premierleague/app/helpers/referees_helper.rb
module RefereesHelper
end

premierleague/app/views/about/about.html.erb
<h1>About</h1>

<%= image_tag("About.jpg") %>

premierleague/app/views/clubs/club.html.erb
<h1>Clubs</h1>

<nav class="float-right mt-2">
  <ul class="pagination pagination-sm">

    <li class="page-item">
      <a class="page-link" href="/clubs">First</a>
    </li>

    <% for i in 1..3 do %>
      <% if @page.to_i == i%>
      <li class="page-item active">
        <a remote="false" class="page-link"><%= i %></a>
      </li>
      <% else %>
      <li class="page-item">
        <a rel="next" class="page-link" href="/clubs?page=<%= i %>"><%= i %></a>
      </li>
      <% end %>
    <% end %>
    <li class="page-item">
      <a class="page-link" href="/clubs?page=3">Last</a>
    </li>
  </ul>
</nav>
<table class="table">
  <thead class="thead-light">
    <th>Position</th>
    <th>Image</th>
	  <th>Club</th>
    <th></th>
  </thead>
  <%
    temp = 1
    if @page.to_i == 1
      i = 1
    else
      i = (@page.to_i - 1) * 7 + 1
    end
  %>
  <% @clubs.each do |club| %>
    <% if temp >= i and temp < (i + 7) %>
      <tr>
        <td><%= temp %></td>
        <td><%= image_tag(club.ClubName + ".jpg") %></td>
        <td><%= link_to club.ClubName, clubs_show_url(club.ClubName) %></td>
      </tr>
    <% end %>

    <% if temp == (i + 7)
        break
      else
        temp += 1
      end %>

  <% end %>
</table>

premierleague/app/views/clubs/show.html.erb
<div class="row">
  <div class="col-12 col-sm-6">
    <%= image_tag(@club.ClubName + ".jpg", class: 'rounded mx-auto d-block', size: '300x300') %>
  </div>
  <div class="col">
    <h2 class="mb-3"> <%= @club.ClubName %> </h2>
    <p><strong> Played: </strong> <%= @club.Played %> </p>
    <p><strong> Won: </strong> <%= @club.Won %> </p>
    <p><strong> Drawn: </strong> <%= @club.Drawn %> </p>
    <p><strong> Lost: </strong> <%= @club.Lost %> </p>
    <p><strong> Goal For: </strong> <%= @club.GoalFor %> </p>
    <p><strong> Goal Against: </strong> <%= @club.GoalAgainst %> </p>
    <p><strong> Goal Difference: </strong> <%= @club.GoalDifference %> </p>
    <p><strong> Point: </strong> <%= @club.Point %> </p>
  </div>
</div>

premierleague/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Premierleague</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-xl navbar-dark bg-dark">
      <a class="navbar-brand" href="/">Premier League 2018 - 2019</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <%= active_link_to 'Clubs', clubs_path, wrap_tag: :li, wrap_class: 'nav-item', class: 'nav-link' %>
            <%= active_link_to 'Matches', matches_path, wrap_tag: :li, wrap_class: 'nav-item', class: 'nav-link' %>
            <%= active_link_to 'Referees', referees_path, wrap_tag: :li, wrap_class: 'nav-item', class: 'nav-link' %>
            <%= active_link_to 'Match Dates', matchdates_path, wrap_tag: :li, wrap_class: 'nav-item', class: 'nav-link' %>
            <%= active_link_to 'About', about_path, wrap_tag: :li, wrap_class: 'nav-item', class: 'nav-link' %>
        </ul>
        <form class="form-inline mt-2 mt-md-0" action="/search" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="✓">
          <input type="text" name="q" id="q" class="form-control mr-sm-2" placeholder="Search for Club Matches" >
          <input type="submit" name="commit" value="Search" class="btn btn-outline-success my-2 my-sm-0" data-disable-with="Search" >
        </form>
      </div>
    </nav>
    <div> <%= yield %> </div>
  </body>
</html>

premierleague/app/views/match_dates/edit.html.erb
<h1>MatchDates#edit</h1>
<p>Find me in app/views/match_dates/edit.html.erb</p>

premierleague/app/views/match_dates/index.html.erb
<h1>MatchDates</h1>

<nav class="float-right mt-2">
  <ul class="pagination pagination-sm">
    <li class="page-item">
      <a class="page-link" href="/matchdates">First</a>
    </li>

    <% for i in 1..9 do %>
      <% if @page.to_i == i%>
      <li class="page-item active">
        <a remote="false" class="page-link"> <%= i %> </a>
      </li>
      <% else %>
      <li class="page-item">
        <a rel="next" class="page-link" href="/matchdates?page=<%= i %>" ><%= i %></a>
      </li>
      <% end %>
    <% end %>

    <li class="page-item">
      <a class="page-link" href="/matchdates?page=9">Last</a>
    </li>
  </ul>
</nav>

<table class="table">
  <thead class="thead-light">
    <th>Date Of Match</th>
    <th>Temperature</th>
    <th></th>
  </thead>

  <%
    temp = 1
    if @page.to_i == 1
      i = 1
    else
      i = (@page.to_i - 1) * 12 + 1
    end
  %>

  <% @matchdates.each do |matchdate| %>
    <% if temp >= i and temp < (i + 12) %>
      <tr>
        <td><%= matchdate.match_date_id %></td>
        <td><%= matchdate.Temperature %></td>
        <td><%= link_to "Show Matches", "/matchdates/#{matchdate.match_date_id}", class: 'btn btn-outline-success' %></td>
      </tr>
    <% end %>

    <% if temp == (i + 12)
        break
      else
        temp += 1
      end %>
  <% end %>
</table>

premierleague/app/views/match_dates/new.html.erb
<h1>MatchDates#new</h1>
<p>Find me in app/views/match_dates/new.html.erb</p>

premierleague/app/views/match_dates/show.html.erb
<h1>Match Date - <%= @matchdate.match_date_id %></h1>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th>Date</th>
      <th>Home Team</th>
      <th>Away Team</th>
      <th>Home Goal</th>
      <th>Away Goal</th>
      <th>Referee</th>
    </tr>
  </thead>

  <% @matches.each do |match| %>

    <tr>
      <td><%= match.match_date_id %></td>
      <td><%= match.HomeTeam %></td>
      <td><%= match.AwayTeam %></td>
      <td><%= match.HomeGoal %></td>
      <td><%= match.AwayGoal %></td>
      <td><%= link_to match.referee.RefereeName, referees_show_url(match.referee.refereeid) %></td>
    </tr>
  <% end %>
</table>

premierleague/app/views/matchs/edit.html.erb
<h1>Matchs#edit</h1>
<p>Find me in app/views/matchs/edit.html.erb</p>

premierleague/app/views/matchs/index.html.erb
<h1>Matches</h1>

<nav class="float-right mt-2">
  <ul class="pagination pagination-sm">
    <li class="page-item">
      <a class="page-link" href="/matches">First</a>
    </li>

    <% for i in 1..10 do %>
      <% if @page.to_i == i%>
      <li class="page-item active">
        <a class="page-link"> <%= i %> </a>
      </li>
      <% else %>
      <li class="page-item">
        <a rel="next" class="page-link" href="/matches?page=<%= i %>" ><%= i %></a>
      </li>
      <% end %>
    <% end %>

    <li class="page-item">
      <a class="page-link" href="/matches?page=10">Last</a>
    </li>
  </ul>
</nav>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th>Date</th>
      <th>Home Team</th>
      <th>Away Team</th>
      <th>Home Goal</th>
      <th>Away Goal</th>
      <th>Referee</th>
    </tr>
  </thead>

  <%
    temp = 1
    if @page.to_i == 1
      i = 1
    else
      i = (@page.to_i - 1) * 38 + 1
    end
  %>

  <% @matches.each do |match| %>

    <% if temp >= i and temp < (i + 38) %>
      <tr>
        <td><%= match.match_date_id %></td>
        <td><%= link_to match.HomeTeam, clubs_show_url(match.HomeTeam)%></td>
        <td><%= link_to match.AwayTeam, clubs_show_url(match.HomeTeam)%></td>
        <td><%= match.HomeGoal %></td>
        <td><%= match.AwayGoal %></td>
        <td><%= link_to match.referee.RefereeName, referees_show_url(match.referee.refereeid) %></td>
      </tr>
    <% end %>

    <% if temp == (i + 38)
        break
      else
        temp += 1
      end %>
  <% end %>
</table>

premierleague/app/views/matchs/new.html.erb
<h1>Matchs#new</h1>
<p>Find me in app/views/matchs/new.html.erb</p>

premierleague/app/views/matchs/show.html.erb
<h1>Search Results</h1>

<p>Your search for "<%= @clubsearch %>" found <%= @count %> matches </p>

<% if @count > 0 %>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th>Date</th>
      <th>Home Team</th>
      <th>Away Team</th>
      <th>Home Goal</th>
      <th>Away Goal</th>
      <th>Referee</th>
    </tr>
  </thead>

  <% @searchmatches.each do |match| %>
    <tr>
      <td><%= match.match_date_id %></td>
      <td><%= match.HomeTeam %></td>
      <td><%= match.AwayTeam %></td>
      <td><%= match.HomeGoal %></td>
      <td><%= match.AwayGoal %></td>
      <td><%= link_to match.referee.RefereeName, referees_show_url(match.referee.refereeid) %></td>
    </tr>
  <% end %>
<% end %>
</table>

premierleague/app/views/referees/edit.html.erb
<h1>Referees#edit</h1>
<p>Find me in app/views/referees/edit.html.erb</p>

premierleague/app/views/referees/index.html.erb
<h1>Referees</h1>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th>Referee Id</th>
      <th>Name</th>
      <th>Age</th>
      <th></th>
    </tr>
  </thead>

  <% @referees.each do |referee| %>
    <tr>
      <td><%= referee.refereeid %></td>
      <td><%= referee.RefereeName %></td>
      <td><%= referee.Age %></td>
      <td><%= link_to "Show Matches", "/referees/matches/#{referee.refereeid}", class: 'btn btn-outline-success' %></td>
    </tr>
  <% end %>
</table>

premierleague/app/views/referees/new.html.erb
<h1>Referees#new</h1>
<p>Find me in app/views/referees/new.html.erb</p>

premierleague/app/views/referees/refereematch.html.erb
<h1> Referee <%= @referee.RefereeName %> </h1>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th>Date</th>
      <th>Home Team</th>
      <th>Away Team</th>
      <th>Home Goal</th>
      <th>Away Goal</th>
      <th>Referee</th>
    </tr>
  </thead>

  <% @matches.each do |match| %>

    <tr>
      <td><%= match.match_date_id %></td>
      <td><%= match.HomeTeam %></td>
      <td><%= match.AwayTeam %></td>
      <td><%= match.HomeGoal %></td>
      <td><%= match.AwayGoal %></td>
      <td><%= link_to match.referee.RefereeName, referees_show_url(match.referee.refereeid) %></td>
    </tr>
  <% end %>
</table>

premierleague/app/views/referees/show.html.erb
<h1>Referees</h1>

<table class="table">
  <tr>
    <th>Referee Id</th>
    <th>Name</th>
	  <th>Age</th>
    <th></th>
  </tr>
  <tr>
    <td><%= @referee.refereeid %></td>
    <td><%= @referee.RefereeName %></td>
    <td><%= @referee.Age %></td>
    <td><%= link_to "Show Matches", "/referees/matches/#{@referee.refereeid}", class: 'btn btn-outline-success' %></td>
  </tr>
</table>